from .m9_prompt_nodes import NODE_CLASS_MAPPINGS as PROMPT_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NAME_MAPPINGS
from .m9_fit_pose_node import NODE_CLASS_MAPPINGS as FITPOSE_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as FITPOSE_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**PROMPT_CLASS_MAPPINGS, **FITPOSE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**PROMPT_NAME_MAPPINGS, **FITPOSE_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
