from .m9_prompt_nodes import NODE_CLASS_MAPPINGS as PROMPT_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NAME_MAPPINGS
from .m9_fit_pose_node import NODE_CLASS_MAPPINGS as FITPOSE_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as FITPOSE_NAME_MAPPINGS
from .m9_prefix_node import NODE_CLASS_MAPPINGS as PREFIX_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as PREFIX_NAME_MAPPINGS
from .m9_step_replace_node import NODE_CLASS_MAPPINGS as STEPREPLACE_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as STEPREPLACE_NAME_MAPPINGS
from .m9_crop_ratio_node import NODE_CLASS_MAPPINGS as CROPRATIO_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as CROPRATIO_NAME_MAPPINGS
from .m9_scale_factor_node import NODE_CLASS_MAPPINGS as SCALEFACTOR_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as SCALEFACTOR_NAME_MAPPINGS
from .m9_eval_string_node import NODE_CLASS_MAPPINGS as EVALSTRING_CLASS_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as EVALSTRING_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**PROMPT_CLASS_MAPPINGS, **FITPOSE_CLASS_MAPPINGS, **PREFIX_CLASS_MAPPINGS, **STEPREPLACE_CLASS_MAPPINGS, **CROPRATIO_CLASS_MAPPINGS, **SCALEFACTOR_CLASS_MAPPINGS, **EVALSTRING_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**PROMPT_NAME_MAPPINGS, **FITPOSE_NAME_MAPPINGS, **PREFIX_NAME_MAPPINGS, **STEPREPLACE_NAME_MAPPINGS, **CROPRATIO_NAME_MAPPINGS, **SCALEFACTOR_NAME_MAPPINGS, **EVALSTRING_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
